config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  resources :shops do
    resources :comments
  end

  resources :items

  match 'recommends' => 'shops#recommends', :as => 'recommends'

  root :to => 'shops#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :shop
  attr_accessible :body, :commenter
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :average_rating, :description, :followers, :name, :price, :sold_count, :qty

  belongs_to :shop

  scope :hot_items, order("sold_count desc").limit(10)
end

app/models/job_level.rb
class JobLevel < ActiveRecord::Base
  attr_accessible :name
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :address, :description, :logo, :name, :slogan, :weight, :tags_attributes
  
  validates :name, :presence => true

  has_many :comments, :dependent => :destroy
  has_many :items, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true, 
  									:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

	scope :recommend_shops, where(:is_recommended => true)

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :shop
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with :name => 'jerry', :password => '123', :only => 'destroy'
	
	def create
		@shop = Shop.find(params[:shop_id])
		@comment = @shop.comments.create(params[:comment])
		redirect_to shop_path(@shop)
	end

	def destroy
		@shop = Shop.find(params[:shop_id])
		@comment = @shop.comments.find(params[:id])
		@comment.destroy
		redirect_to shop_path(@shop)
	end


end

app/controllers/shops_controller.rb
# coding: utf-8
class ShopsController < ApplicationController
  # before_filter :authenticate_user!, :only => [:recommends]  
  # GET /shops
  # GET /shops.json

  def index
    @shops = Shop.all
    # binding.pry
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shops }
    end
  end

  # TODO: make this 1 at beginning, and 3 afterwards
  def recommends
    @recommend_shops = Shop.recommend_shops
    @hot_items = Item.hot_items
    @title = "推荐商店"

    respond_to do |format|
      format.html
      format.json { render :json => @recommend_shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])
    # binding.pry
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper
	title = "您身边的社区帮手"

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
	def join_tags(shop)
		shop.tags.map { |t| t.name }.join(', ')
	end
end

app/views/comments/_comment.html.erb
<p>
	<b>Commenter:</b>
	<%= comment.commenter %>
</p>

<p>
	<b>Comment:</b>
	<%= comment.body %>
</p>

<p>
	<%= link_to "Remove Comment", [comment.shop, comment], 
									:confirm => "Are you sure",
									:method => :delete
									 %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@shop, @shop.comments.build]) do |f| %>
	
  <div class="field">
    <%= f.label "Your name", :commenter %> <br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label "Comment", :body %> <br />
    <%= f.text_area :body %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>  

<% end %>

app/views/common/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert-message info">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert-message error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert-message warning">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/common/_footer.html.erb
<div id="footer">
	<ul>
		<li><%= link_to "合作", "/hezuo" %></li>
		<li><%= link_to "关于", "/hezuo" %></li>
		<li><%= link_to "联系我们", "/hezuo" %></li>
		<li><%= link_to "客服", "/hezuo" %></li>
	</ul>
</div>

app/views/common/_header.html.erb
<div id="search">
	<input type="text" class="large" />
	<button name="search" id="do_search" class="button">搜索</button>
</div>

app/views/common/_menu.html.erb
<ul class="nav">
  <li><%= link_to "首页", root_path %></li>
  <li><a href="/about">探索发现</a></li>
  <li><a href="/about">求购</a></li>
</ul>
<ul class="nav pull-right">
<% if current_user %>
	<li><%= link_to "Edit account", edit_user_registration_path(current_user) %></a></li>
	<li><a href="users/sign_out">Logout</a></li>
<% else %>
	<li><a href="users/sign_in">Sign in</a></li>
	<li><a href="users/sign_up">Sign up</a></li>
<% end %>		
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><%= content_for?(:title) ? yield(:title) : "真心贴心的社区" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">爱上家</a>
      <%= render :partial => 'common/menu' %>
    </div>
  </div>
</div>


<div class="container">
  <div class="content">
    <div class="page-header">
      <%= render :partial => 'common/header' %>
    </div>
    <div class="row">
      <div class="span12">
        <%= render :partial => 'common/flashes' %>
        <%= yield %>
      </div>
    </div>
    <footer>
    	<%= render :partial => 'common/footer' %>
    </footer>
  </div>
</div>


</body>
</html>

app/views/shops/_form.html.erb
<% @shop.tags.build %>
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slogan %><br />
    <%= f.text_field :slogan %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>

  <h2>Tags</h2>
  <%= render :partial =>  "tags/form",
             :locals => {:form => f}
  %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Slogan</th>
    <th>Address</th>
    <th>Description</th>
    <th>Logo</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= shop.name %></td>
    <td><%= shop.slogan %></td>
    <td><%= shop.address %></td>
    <td><%= shop.description %></td>
    <td><%= shop.logo %></td>
    <td><%= shop.weight %></td>
    <td><%= link_to 'Show', shop %></td>
    <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
    <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/recommends.html.erb
<div id="recommend_shops">
	<ul>
	<% @recommend_shops.each do |s| %>
		<li>
			<div class="recommend_shop">
				<%= s.name %>
			</div>
		</li>
	<% end %>
	</ul>
</div>

<div id="hot-items">
	<ul>
	<% @hot_items.each do |s| %>	
		<li>
			<div class="hot_item">
				<%= i.name %>
			</div>
		</li>
	<% end %>
	</ul>
</div>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p id='foo'>
  <b>Name:</b>
  <%= @shop.name %>
</p>

<p>
  <b>Slogan:</b>
  <%= @shop.slogan %>
</p>

<p>
  <b>Address:</b>
  <%= @shop.address %>
</p>

<p>
  <b>Description:</b>
  <%= @shop.description %>
</p>

<p>
  <b>Logo:</b>
  <%= @shop.logo %>
</p>

<p>
  <b>Weight:</b>
  <%= @shop.weight %>
</p>

<p>
 <b>Tags:</b>
 <%= join_tags(@shop) %>
</p>

<h2>Comments</h2>
<%= render @shop.comments %>

<h2>Add a comment:</h2>

<%= render "comments/form" %>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>

<div class="field">
	<%= tag_form.label :name, 'Tag:' %>
	<%= tag_form.text_field :name %>
</div>

	<% unless tag_form.object.nil? || tag_form.object.new_record? %>
		<div class="filed">
			<%= tag_form.label :_destroy, 'Remove:' %>
			<%= tag_form.check_box :_destroy %>
		</div>
	<% end  %>
<% end  %>	